// flow-typed signature: 570ce424ec93849ca9838f42bc39e027
// flow-typed version: <<STUB>>/buffer-map_v0.0.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'buffer-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare class BufferMap<V> extends Map<Buffer, V> {}
declare class BufferSet extends Set<Buffer> {}

declare module "buffer-map" {
  declare module.exports: {
    BufferMap: Class<BufferMap<any>>,
    BufferSet: Class<BufferSet>
  };
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "buffer-map/lib/buffer-map" {
  declare module.exports: $Exports<"buffer-map">;
}

// Filename aliases
declare module "buffer-map/lib/buffer-map.js" {
  declare module.exports: $Exports<"buffer-map/lib/buffer-map">;
}
